version: '3.7'

services:
  zookeeper:
    image: elevy/zookeeper:latest
    container_name: zookeeper
    ports:
      - "2181:2181"

  kafka:
    image: wurstmeister/kafka:latest
    ports:
      - "9092:9092"
    env_file:
      - env/kafka.env
    depends_on:
      - zookeeper
    links:
      - zookeeper:zookeeper

  service-configuration:
    build:
      dockerfile: ServiceConfigDockerFile
    image: service-configuration
    container_name: service-configuration
    ports:
      - "1414:1414"

  eureka-server:
    image: service-discovery.jar
    container_name: service_discovery
    build:
      context: .
      dockerfile: ServiceDiscoveryDockerFile
    ports:
      - "8761:8761"
    env_file:
      - env/service-discovery.env

  api-gateway:
    image: api-gateway
    container_name: api-gateway
    build:
      dockerfile: GatewayDockerFile
    ports:
      - "1211:1211"
    depends_on:
      - eureka-server
      - resource-service
      - song-service
    env_file:
      - env/api-gateway.env

  resource-processor:
    image: 'resource-processor.jar'
    container_name: 'resource-processor'
    build:
      context: .
      dockerfile: ProcessorDockerFile
    ports:
      - "1113:1113"
    depends_on:
      - song-service
      - resource-service
      - kafka
    links:
      - service-configuration
    env_file:
      - env/resource-processor.env

  msa_resources_db:
    image: 'postgres:14-alpine3.14'
    container_name: 'msa_resources_db'
    restart: always
    env_file:
      - env/resources-db.env

  resource-service:
    image: 'resource-service.jar'
    container_name: 'resource-service'
    build:
      context: .
      dockerfile: ResourceDockerFile
    ports:
      - "1111:1111"
    depends_on:
      - msa_resources_db
      - kafka
      - eureka-server
    env_file:
      - env/resource-service.env

  song_service_db:
    image: 'postgres:14-alpine3.14'
    container_name: 'song_service_db'
    restart: always
    env_file:
      - env/song-db.env

  song-service:
    image: 'song-service.jar'
    container_name: 'song-service'
    build:
      context: .
      dockerfile: SongDockerFile
    ports:
      - "1112:1112"
    depends_on:
      - song_service_db
      - eureka-server
    env_file:
      - env/song-service.env

  storage_service_db:
    image: 'postgres:14-alpine3.14'
    container_name: 'storage_service_db'
    restart: always
    env_file:
      - env/storage-db.env

  storage-service:
    image: 'storage-service.jar'
    container_name: 'storage-service'
    build:
      context: .
      dockerfile: StorageDockerFile
    ports:
      - "1115:1115"
    depends_on:
      - storage_service_db
      - eureka-server
    env_file:
      - env/storage-service.env